.TH "src/preproc/sudoku_detection Directory Reference" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/preproc/sudoku_detection Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsudoku_split\&.c\fP"
.br
.ti -1c
.RI "file \fBsudoku_split\&.h\fP"
.br
.in -1c
