.TH "src Directory Reference" 3 "Tue Nov 22 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcli\fP"
.br
.ti -1c
.RI "directory \fBnetwork\fP"
.br
.ti -1c
.RI "directory \fBpainter\fP"
.br
.ti -1c
.RI "directory \fBpreproc\fP"
.br
.ti -1c
.RI "directory \fBsolver\fP"
.br
.ti -1c
.RI "directory \fBui\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
