.TH "src/network Directory Reference" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/network Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunction\&.c\fP"
.br
.ti -1c
.RI "file \fBfunction\&.h\fP"
.br
.ti -1c
.RI "file \fBnetwork\&.c\fP"
.br
.ti -1c
.RI "file \fBnetwork\&.h\fP"
.br
.in -1c
