.TH "src/preproc/color_removal Directory Reference" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/preproc/color_removal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolor_removal\&.c\fP"
.br
.ti -1c
.RI "file \fBcolor_removal\&.h\fP"
.br
.in -1c
