.TH "Cell" 3 "Tue Nov 22 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBsolver\&.c\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Cell::x"

.PP
Definition at line \fB9\fP of file \fBsolver\&.c\fP\&.
.SS "int Cell::y"

.PP
Definition at line \fB10\fP of file \fBsolver\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
