.TH "layer_t" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layer_t \- A struct representing a layer in the network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBneuron_t\fP ** \fBneurons\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "\fBlayer_activation_t\fP \fBact\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a layer in the network\&. 
.PP
Definition at line \fB46\fP of file \fBnetwork\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBlayer_activation_t\fP layer_t::act"
The number of neurons in the layer\&. 
.PP
Definition at line \fB50\fP of file \fBnetwork\&.h\fP\&.
.SS "size_t layer_t::count"
The allocated neurons in the layer\&. 
.PP
Definition at line \fB49\fP of file \fBnetwork\&.h\fP\&.
.SS "\fBneuron_t\fP** layer_t::neurons"

.PP
Definition at line \fB48\fP of file \fBnetwork\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
