.TH "layer_activation_t" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layer_activation_t \- The struct containing all info required about the activation function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBactivation_t\fP \fBactivation\fP"
.br
.ti -1c
.RI "\fBactivation_t\fP \fBdactivation\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The struct containing all info required about the activation function\&. 
.PP
Definition at line \fB25\fP of file \fBnetwork\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBactivation_t\fP layer_activation_t::activation"

.PP
Definition at line \fB27\fP of file \fBnetwork\&.h\fP\&.
.SS "\fBactivation_t\fP layer_activation_t::dactivation"
The activation function\&. 
.PP
Definition at line \fB28\fP of file \fBnetwork\&.h\fP\&.
.SS "const char* layer_activation_t::name"
The derivative of the activation function 
.PP
Definition at line \fB29\fP of file \fBnetwork\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
