.TH "src/main.c" 3 "Sat Oct 29 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <err\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&./cli/parser\&.h'\fP
.br
\fC#include '\&./network/function\&.h'\fP
.br
\fC#include '\&./network/network\&.h'\fP
.br
\fC#include '\&./solver/solver\&.h'\fP
.br
\fC#include '\&./utils/matrices/matrix\&.h'\fP
.br
\fC#include '\&./utils/mnist/loader\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.ti -1c
.RI "#define \fBPRINT_PARAM\fP(params,  key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PRINT_PARAM(params, key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"

.PP
Definition at line \fB141\fP of file \fBmain\&.c\fP\&.
.SS "#define UNUSED(x)   (void)(x)"

.PP
Definition at line \fB14\fP of file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB308\fP of file \fBmain\&.c\fP\&.
.PP
.nf
309 {
310     UNUSED(print_params);
311     UNUSED(show_results);
312     UNUSED(train_xor);
313     char mode;
314     params_t params = parse_params(argc, argv, &mode);
315     if (params == NULL)
316     {
317         errx(-1, "missing subcommand");
318     }
319 
320     signal(SIGINT, int_handler);
321     if (mode == TRAIN_MODE)
322     {
323         train(params);
324     }
325     else if (mode == TEST_MODE)
326     {
327         test(params);
328     }
329 
330     return 0;
331 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
