.TH "src/main.c" 3 "Fri Nov 11 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <err\&.h>\fP
.br
\fC#include <gtk/gtk\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&./cli/parser\&.h'\fP
.br
\fC#include '\&./network/function\&.h'\fP
.br
\fC#include '\&./network/network\&.h'\fP
.br
\fC#include '\&./solver/solver\&.h'\fP
.br
\fC#include '\&./ui/ui\&.h'\fP
.br
\fC#include '\&./utils/img_loader/loader\&.h'\fP
.br
\fC#include '\&./utils/matrices/matrix\&.h'\fP
.br
\fC#include '\&./utils/mnist/loader\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.ti -1c
.RI "#define \fBPRINT_PARAM\fP(params,  key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PRINT_PARAM(params, key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"

.PP
Definition at line 144 of file main\&.c\&.
.SS "#define UNUSED(x)   (void)(x)"

.PP
Definition at line 17 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 311 of file main\&.c\&.
.PP
.nf
312 {
313     UNUSED(print_params);
314     UNUSED(show_results);
315     UNUSED(train_xor);
316     char mode;
317     params_t params = parse_params(argc, argv, &mode);
318     if (argc == 2)
319     {
320         return solve(argv[1]);
321     }
322     if (params == NULL)
323     {
324         open_ui();
325         return 0;
326     }
327     signal(SIGINT, int_handler);
328     if (mode == TRAIN_MODE)
329     {
330         train(params);
331     }
332     else if (mode == TEST_MODE)
333     {
334         test(params);
335     }
336 
337     return 0;
338 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
