.TH "src/main.c" 3 "Tue Nov 22 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <err\&.h>\fP
.br
\fC#include <gtk/gtk\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&./cli/parser\&.h'\fP
.br
\fC#include '\&./network/function\&.h'\fP
.br
\fC#include '\&./network/network\&.h'\fP
.br
\fC#include '\&./solver/solver\&.h'\fP
.br
\fC#include '\&./ui/ui\&.h'\fP
.br
\fC#include '\&./utils/img_loader/loader\&.h'\fP
.br
\fC#include '\&./utils/matrices/matrix\&.h'\fP
.br
\fC#include '\&./utils/mnist/loader\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.ti -1c
.RI "#define \fBPRINT_PARAM\fP(params,  key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PRINT_PARAM(params, key)       printf('%s: \\'%d\\' \-> %s\\n', #key, key, params[key])"

.PP
Definition at line \fB144\fP of file \fBmain\&.c\fP\&.
.SS "#define UNUSED(x)   (void)(x)"

.PP
Definition at line \fB17\fP of file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB341\fP of file \fBmain\&.c\fP\&.
.PP
.nf
342 {
343     UNUSED(print_params);
344     UNUSED(show_results);
345     UNUSED(train_xor);
346     char mode;
347     params_t params = parse_params(argc, argv, &mode);
348     if (argc == 2)
349     {
350         return solve(argv[1], 16);
351     }
352     if (params == NULL)
353     {
354         open_ui();
355         return 0;
356     }
357     signal(SIGINT, int_handler);
358     if (mode == TRAIN_MODE)
359     {
360         train(params);
361     }
362     else if (mode == TEST_MODE)
363     {
364         test(params);
365     }
366     else if (mode == CONVERT_MODE)
367     {
368         cli_convert(params);
369     }
370     free(params);
371 
372     return 0;
373 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
