.TH "matrix_t" 3 "Tue Nov 22 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double * \fB_elements\fP"
.br
.ti -1c
.RI "size_t \fBrows\fP"
.br
.ti -1c
.RI "size_t \fBcolumns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBmatrix\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double* matrix_t::_elements"

.PP
Definition at line \fB11\fP of file \fBmatrix\&.h\fP\&.
.SS "size_t matrix_t::columns"
the number of rows 
.PP
Definition at line \fB13\fP of file \fBmatrix\&.h\fP\&.
.SS "size_t matrix_t::rows"
the content of the matrix 
.PP
Definition at line \fB12\fP of file \fBmatrix\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
