.TH "network_t" 3 "Tue Nov 22 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network_t \- A struct representing a neural network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlayer_t\fP ** \fBlayers\fP"
.br
.ti -1c
.RI "size_t \fBlayer_count\fP"
.br
.ti -1c
.RI "size_t \fBinputs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a neural network\&. 
.PP
Definition at line \fB58\fP of file \fBnetwork\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t network_t::inputs"
The count of layers in the network\&. 
.PP
Definition at line \fB62\fP of file \fBnetwork\&.h\fP\&.
.SS "size_t network_t::layer_count"
The array of layers in the network\&. 
.PP
Definition at line \fB61\fP of file \fBnetwork\&.h\fP\&.
.SS "\fBlayer_t\fP** network_t::layers"

.PP
Definition at line \fB60\fP of file \fBnetwork\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
