.TH "neuron_t" 3 "Sun Oct 30 2022" "OCR-Lezcollitade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
neuron_t \- A struct representing a neuron in the network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmatrix_t\fP * \fBweights\fP"
.br
.ti -1c
.RI "double \fBbias\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a neuron in the network\&. 
.PP
Definition at line \fB35\fP of file \fBnetwork\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double neuron_t::bias"
The row vector of the weights of each synapse before the neuron 
.PP
Definition at line \fB39\fP of file \fBnetwork\&.h\fP\&.
.SS "\fBmatrix_t\fP* neuron_t::weights"

.PP
Definition at line \fB37\fP of file \fBnetwork\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OCR-Lezcollitade from the source code\&.
